### ISSUE TITLE
IDs for selectors

### ISSUE THREAD

**Issue by jcuenod** [gasparesganga/jquery-message-box#1]
I want to increase the z-index of the overlay box (more generally someone may want to just style it differently - say with black rather than white transparency). I use a css linter that complains about "#messagebox_overlay" saying, "Don't use IDs in selectors". It's just a linting thing but it would be cool if message box followed those practices.

**Comment by gasparesganga** [comment]
Hi. You've got two different questions here:

1) You can of course customize all the jQuery MessageBox CSS rules you like, the main CSS file is fully commented and structured in a way that it's should be very straightforward to implement your changes.
For example, if you wanted a black transparency instead of a white one, just change this:

``` css
#messagebox_overlay {
    background-color    : rgba(255,255,255,0.6);
}
```

to this:

``` css
#messagebox_overlay {
    background-color    : rgba(0,0,0,0.6); 
}
```

2) I've heard about those CSS Linters and their arbitrary assumptions... Have you asked yourself _why_ you shouldn't be using CSS IDs?
I'll answer that for you: there's no reason if your code is well structured actually.
The lack of valid arguments is embarassing for them (those CSS linters), and what is worse is that many people follow those _practices_ without even trying to understand if there's a motivation behind them.
The point is: **It would NOT be cool at all if jQuery MessageBox (and everything else actually) blindly followed those practices**, trust me, CSS ID's are cool.
